using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace GcodeDivider
{
    public partial class note : Form
    {
        public note()
        {
            InitializeComponent();
        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {

        }
        public bool boxCheck = false;

        private void btnOK_Click(object sender, EventArgs e)
        {
            if (checkBox1.Checked)
            {
                boxCheck = true;
            }

            this.Close();
        }

        private void note_Load(object sender, EventArgs e)
        {
            String cp = Environment.NewLine;
            txtNote.Text = "";
            txtNote.Text += "This program is given without any guaranteed." + cp;
            txtNote.Text += " The purpose of this program is read a Gcode generated by a slicer like Cura and divide it in  subsequential files to " +
                "let the user pause the printer at the end of a file and resume with the next file" + cp + cp;
            txtNote.Text += " For now, the program needs that the slicer put a comment (;LAYER:###) at the start of each layer." +
                "Cura 3.6.0 does this." + cp + cp + "this program had been TESTED ONLY WITH CURA 3.6.0 GCODES";
            txtNote.Text += cp + cp + "this program had been tested only with REPRAP FLAVOUR GCODES";
        }

        private void checkBox1_CheckedChanged(object sender, EventArgs e)
        {
            if (checkBox1.Checked)
                System.IO.File.Create("nostartup.txt");
        }
    }
}
